### ISSUE TITLE
Wild <span> elements in medium-editor output

### ISSUE THREAD

**Issue by JonasDoebertin** [storypioneers/kirby-wysiwyg#1]
Sometimes, when copy and pasting text inside the editor, there are some wild `<span>` elements being added. As they randomly have `line-height` and `font-size` inline styles attached, they might break the pages design.

**Comment by dgdsp** [comment]
an option would be to convert to plaintext via innerTEXT, cf. http://stackoverflow.com/questions/6899659/remove-formatting-from-a-contenteditable-div

**Comment by JonasDoebertin** [comment]
The way the field works is that everytime the user modifies the content within the editor, the whole content is mirrored into a hidden textarea. This happens, since the medium editor uses a `contenteditable` `<div>` and the panel doesn't know how to save these. The panel will save the textarea as the field value instead.

So I guess we have to filter through the textarea and remove all `<span>` elements (only the tags, not the content). The easiest way would be to do this server side, once the user hits the "Save" button. We can't just remove all HTML, since the editor allows for some formatting options that Markdown just don't support, like subscript, superscript, del, ins and mark tags. They are embedded as inline html (which is explicitly allowed in Markdown).

I'll prepare something tomorrow.

**Comment by JonasDoebertin** [comment]
Fixed with 2b9fe86365530b160a16673bf402ce43ec9a931a.
