### ISSUE TITLE
formatting: mark text does not work as expected

### ISSUE THREAD

**Issue by dgdsp** [storypioneers/kirby-wysiwyg#11]
- marked text does not highlight the mark button
- unmarking marked text does not work
- marking of text is not saved
- only when marking the whole line, the mark button is highlighted and the text can be unmarked, the mark button stays active though

_tested on Safari 8.0.3 (10600.3.18) and Chrome 40.0.2214.115 (64-bit)_

![kirby-wysiwyg--mark-button--bug--20150223](https://cloud.githubusercontent.com/assets/293852/6331548/1f093ea4-bb80-11e4-8bde-40fbd4f84f72.gif)

**Comment by JonasDoebertin** [comment]
I'll have a look into this.

**Comment by JonasDoebertin** [comment]
I did some investigations. This is what I found out:

**marked text does not highlight the mark button**

Seems to be an error with the medium-editor script. If you select one character more at the beginning and the end of the marked content, the button is properly highlighted. There should be an issue opened on the editors repo.

**unmarking marked text does not work**

Same as above.

**marking of text is not saved**

You're right. Inserting styles with our three custom buttons (mark, ins. del) doesn't trigger the `input` event on the `contenteditable` `<div>` like the standard buttons do. Should be fixable quite easily. Will work on that.

**only when marking the whole line, the mark button is highlighted and the text can be unmarked, the mark button stays active though**

Related to 1. and 2.

**Comment by JonasDoebertin** [comment]
It seems we can listen to changes made with both the standard and the custom buttons by listening to `DOMSubtreeModified` on the editable element instead of the classic `input` event.

**Comment by JonasDoebertin** [comment]
The other issues are related to the MediumButton script. Unfortunately, that script isn't hosted on GitHub and I wasn't able to contact the author, yet.

**Comment by JonasDoebertin** [comment]
Change of event implemented with 265826bfa0f8c5099570c43462046f75911c9ff1.
