### ISSUE TITLE
Custom buttons selection recognition is off

### ISSUE THREAD

**Issue by JonasDoebertin** [storypioneers/kirby-wysiwyg#13]
Custom buttons may not work as expected when selecting content that has been modified with them.

They don't recognize the selected content correctly.

**Original Description:**
- marked text does not highlight the mark button
- unmarking marked text does not work
- only when marking the whole line, the mark button is highlighted and the text can be unmarked, the mark button stays active though

_tested on Safari 8.0.3 (10600.3.18) and Chrome 40.0.2214.115 (64-bit)_

![kirby-wysiwyg--mark-button--bug--20150223](https://cloud.githubusercontent.com/assets/293852/6331548/1f093ea4-bb80-11e4-8bde-40fbd4f84f72.gif)

**Comment by JonasDoebertin** [comment]
I finally managed to contact the author of the MediumButton extension we're using. Let's see what he says about this issue.

**Comment by dgdsp** [comment]
related MediumButton issues:
- https://github.com/arcs-/MediumButton/issues/2
- https://github.com/arcs-/MediumButton/issues/1

**Comment by dgdsp** [comment]
let's ditch medium-button and use the standard medium-editor way (possibly requiring an upgrade to the current medium-editor)
