### ISSUE TITLE
Linebreak

### ISSUE THREAD

**Issue by janstieler** [storypioneers/kirby-wysiwyg#15]
Hi,
is there an possibility to integrate an linebreak? 
Actually it creates on every break an paragraph.

Cheers

**Comment by dgdsp** [comment]
try entering shift+enter

**Comment by janstieler** [comment]
Hi,
I have, but I got also a paragraph element.

**Comment by dgdsp** [comment]
@JonasDoebertin 

the config setting

```
c::set('field.wysiwyg.double-returns', true);
```

seems to broken due to a bug in html-to-markdown.

**Comment by dgdsp** [comment]
@janstieler 

sorry for the long delay…

you can end a line with two or more spaces to create an empty line.
