### ISSUE TITLE
ul > li > ul - nested lists

### ISSUE THREAD

**Issue by good-idea** [storypioneers/kirby-wysiwyg#25]
Is it possible to create nested lists?

**Comment by JonasDoebertin** [comment]
Correct me if I'm wrong, but afaik, plain markdown doesn't support nested lists.

**Comment by OscarGodson** [comment]
Yes, nested lists work fine:
- Step one
  - Step two
    - Step three

**Comment by OscarGodson** [comment]
This is something we need as well
