### ISSUE TITLE
Images ?

### ISSUE THREAD

**Issue by bugsysop** [storypioneers/kirby-wysiwyg#27]
Is there a way to add image in the text ? I tried to drag image in text area wit Kirby 2.2.3 and this do nothing... Is this function working with previous version of Kirby ?

**Comment by Abzlarson** [comment]
![11887925_10153247986869215_9189830329567046675_n](https://cloud.githubusercontent.com/assets/12075413/12563289/1f25fc7c-c36f-11e5-975f-f4ec9db81ebe.jpg)

**Comment by Abzlarson** [comment]
![11887925_10153247986869215_9189830329567046675_n](https://cloud.githubusercontent.com/assets/12075413/12563303/3c84fa98-c36f-11e5-972b-4555d1c9e20c.jpg)

**Comment by samnabi** [comment]
I can confirm this issue. Would be great to be able to drag-and-drop images into the wysiwyg textarea.

**Comment by stereonom** [comment]
c::set('field.wysiwyg.dragdrop.kirby', true);
c::set('field.wysiwyg.dragdrop.medium', true);

**Comment by OscarGodson** [comment]
I'm still new to Kirby, where do I paste that @stereonom?

**Comment by OscarGodson** [comment]
Whoops, asked too soon. It goes in config.php and then you can drag and drop right into the wysiwyg field! Thanks!

**Comment by bugsysop** [comment]
Thanks... Sorry for taking so many time ;-)
