### ISSUE TITLE
Please some more installation instructions for non-coders

### ISSUE THREAD

**Issue by bertbelgium** [storypioneers/kirby-wysiwyg#36]
I copied the folder to the plugins folder but I can't get it to work.
I keep getting the following error message (after I add a wysiwyg field to  blueprint): "The wysiwyg field is missing. Please add it to your installed fields or remove it from your blueprint."

Can you extend the installation instructions for dummies?

Also an example of the settings in the config.php file would be handy.

**Comment by Giuca** [comment]
Hey there,
just put the folder into fields not into plugins->and call it "wysiwyg". Didi it right now and it worked.

**Comment by bertbelgium** [comment]
Thanks for the idea. Very strange because this is not at all what is explained in the readme.
@JonasDoebertin, please provide some correct (or more detailed) installation instructions for future users.

But I still can't get the buttons (general config) set up. Obviously I don't want the H1 tag to be set by the user but I can't change the buttons. ~~If I try to set them in the blueprints for each page type then I get an error message "Warning: implode(): Invalid arguments passed in /home/.../public_html/kirby/site/fields/wysiwyg/wysiwyg.php on line 196". Again I followed the exact instructions provided. FYI my browser gives a javascript error: [Error] TypeError: undefined is not an object (evaluating 'this.$editor.data('buttons').split') ---- WysiwygEditor — js:110
If I don't add custom buttons (on blueprint) this error doesn't occur.~~ edit: I used a wrong syntax for the blueprints - don't know what I do wrong (or what I should do exactly) in config.php though.

**Comment by sajjadalis** [comment]
Instructions are not right. It's saying i need to put folder in plugins..
http://prntscr.com/cjtqv2

I did exactly that and changed textarea field with wysiwyg in blueprints but it's not working. Same error message as @bertbelgium is getting. Now after reading this topic. I moved whole wysiwyg folder to _panel/app/fields/wysiwyg_ but it's still not working.. Is there any other fields folder or how should i get it working?

**Comment by plaidpowered** [comment]
@Key7i Which version of Kirby are you running? It looks like this plugin would only be compatible with 2.3 and above

**Comment by sajjadalis** [comment]
@plaidpowered i'm using v2.3.2 latest version.. Earlier i moved whole folder to fields and it was not working.. Now i moved only "field" folder to _panel/app/fields/wysiwyg_ and rename it as wysiwyg.. Now i can get on edit page without error but still it's not working.

http://prntscr.com/ckqxbh

**Comment by nyash** [comment]
Here's what worked for me:
1. Download kirby-wysiwyg project as ZIP from github
2. Create /site/fields folder if it doesn't exist
3. Extract kirby-wysiwyg and copy 'fields' folder to /site/fields
4. Rename /site/fields/field to /site/fields/wysiwyg

**Comment by sajjadalis** [comment]
@nyash Thanks a lot for the steps.. It's working now.. I didn't had /site/fields folder and wysiwyg field was added in the wrong place..

I tried to create a pull request for README.md with these steps. It's my first time creating pull request on github. If it's not right way. Then someone can do it. It will make things easier for other users.

**Comment by dgdsp** [comment]
updated the readme for the current version. sry for the complications.
