### ISSUE TITLE
Remove <style> tag to prevent invisible pasted inline CSS

### ISSUE THREAD

**Issue by Ventricule** [storypioneers/kirby-wysiwyg#39]
Hello,

When you paste content from, for exemple, Word, it paste also the inline <style> rules. 
This behavior is invisible for the user but it can broke enterly the website CSS.
So, l.245, in the HTMLToMarkdown params, I added `'remove_nodes' => 'style',` and I think you should add it to the core, don't you think ?

Schuss,
Pierre

**Comment by dgdsp** [comment]
hi Pierre,

great suggestion, added to the dev-branch, thank you!

cheers
